language: python
python:
  - "2.7"


install:

    # command to install dependencies
    - python setup.py install

    # command to install test dependencies
    - pip install -r test-requirements.txt



script:

    # command to run tests - we dont run remote tests since we cant provision vagrant inside travis
    - 'nosetests --nocapture worker_installer.tests.test_fabric_retry_runner:TestLocalRunnerCase'
    - 'nosetests --nocapture worker_installer.tests.test_fabric_retry_runner:TestLocalInstallerCase'