language: python
python:
    - "2.7"

services:
    - rabbitmq

env:
    global:
        - NUMBER_OF_SUITES=3
    matrix:
        - ACTION="run-integration-tests" SUITE_NUMBER=0
        - ACTION="run-integration-tests" SUITE_NUMBER=1
        - ACTION="run-integration-tests" SUITE_NUMBER=2
        - ACTION="test-plugins"
        - ACTION="test-rest-service"
        - ACTION="flake8"
        - ACTION="plugin-installer-py26"
before_script:
        - sudo rabbitmqctl add_user cloudify c10udify
        - sudo rabbitmqctl set_permissions cloudify '.*' '.*' '.*'
        - sudo rabbitmqctl delete_user guest
install:
    - pip install tox
script:
    - ./run-tests.sh $ACTION
