language: java

jdk:
  - openjdk7
  
before_script:
   - "gem install travis-artifacts"

install:
   - "mvn install -DskipTests -f travis-pom.xml"

script:
   - "mvn verify -f travis-pom.xml"

after_success:
  - "test ${TRAVIS_BRANCH} = develop && travis-artifacts upload --path $HOME/.m2/repository/org/cloudifysource/cosmo/orchestrator --target-path travisci"
  - "test ${TRAVIS_BRANCH} = develop && travis-artifacts upload --path $HOME/.m2/repository/org/cloudifysource/cosmo/resource-monitor --target-path travisci"
  - "test ${TRAVIS_BRANCH} = develop && travis-artifacts upload --path $HOME/.m2/repository/org/cloudifysource/cosmo/resource-monitor-api --target-path travisci"
  - "test ${TRAVIS_BRANCH} = develop && travis-artifacts upload --path $HOME/.m2/repository/org/cloudifysource/cosmo/state-cache --target-path travisci"
  - "test ${TRAVIS_BRANCH} = develop && travis-artifacts upload --path $HOME/.m2/repository/org/cloudifysource/cosmo/state-cache-api --target-path travisci"

env:
 global:
   - "ARTIFACTS_AWS_REGION=us-east-1"
   - "ARTIFACTS_S3_BUCKET=cosmo-snapshot-maven-repository"
   - secure: "ZFXmjFGg7wHA+u/8HmhAop6Y4zRJIHdVPvWrYHN3zlV5MuaG/5Zfr7HTzVyK\nGirLlRK3g0trDNnkNWYbnu4gfP1V7sPxv+G9HcP0Ig1hr13Xlh8u0u0yCFjp\nD/fW8nndIPNNi+7xT6KZMhUt+oNxEA31rY4dIVGoU7oHCebhD5U="
   - secure: "bXHI5aPs5VROGRwm44wPT49YzU8oSJ4Y82sl5SyAg7oalRPHeTdm2tv+cjx5\nxRaw9BW0CMYycbqQl3Bt8BuPfaQKgNpGdweJTFSdDKNB/rH0qnqFdBYLtbL3\nOv0UJp04XGUidfDjzCtS7uhrF5p/UFKewoFGaYuelasZ0wfCKFU="

# Comments:
# 
#  Finding the public key used for encryption: https:# api.travis-ci.org/repos/CloudifySource/cosmo-manager/key
#  Encrypting: http://about.travis-ci.org/docs/user/build-configuration/#Secure-environment-variables
#              travis encrypt -r CloudifySource/cosmo-manager ARTIFACTS_AWS_ACCESS_KEY_ID=xxxxx
#  Don't use your direct AWS credentials. Create limited credentials with Amazon IAM
#  How to upload travis artifacts: https:# github.com/travis-ci/travis-artifacts
#  How to find local maven repo: http:# stackoverflow.com/questions/5916157/how-to-get-the-maven-local-repo
#  Do not use mvn -X switch as it exposes the environment variables and exposes the secret key.