language: python

services:
  - rabbitmq # will start rabbitmq-server

python:
  - "2.7"


install:


    # celery needs the /dev/shm device for billiard semaphore functionality.
    # this device is not mounted by default on travis hosts.
    # see https://github.com/travis-ci/travis-core/issues/187#issuecomment-13682856
    - sudo test -d /dev/shm && sudo rm -rf /dev/shm
    - sudo ln -Tsf /{run,dev}/shm

    # command to install dependencies
    - pip install --process-dependency-links .

    # command to install test dependencies
    - pip install -r test-requirements.txt

    - sudo pip install flake8



script:
    - flake8 .
    - nosetests worker_installer.tests.test_worker_installer:TestLocalInstallerCase --nologcapture --nocapture

