language: java

jdk:
  - openjdk7

services:
  - rabbitmq

before_script:
   - "wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.0.1.deb"
   - "sudo dpkg -i elasticsearch-1.0.1.deb"
   - "export PATH=$PATH:/usr/share/elasticsearch/bin"      
   - 'sudo mkdir -p /usr/share/elasticsearch/data'
   - "sudo chmod 777 /usr/share/elasticsearch/data"
   - "wget http://aphyr.com/riemann/riemann_0.2.2_all.deb"
   - "sudo dpkg -i riemann_0.2.2_all.deb"
   - "sudo touch /var/log/riemann/riemann.log"
   - "sudo chmod 666 /var/log/riemann/riemann.log"
   - "sudo test -d /dev/shm && sudo rm -rf /dev/shm"
   - "sudo ln -Tsf /{run,dev}/shm"
   - "sudo chmod 777 /dev/shm" # for celery worker

install:
   - "rvm install ruby-2.1.0"
   - "rvm use ruby-2.1.0"
   - "rvm --default use ruby-2.1.0"
   - "gem install bundler"
   - "cd workflow-service; bundle install; cd .."
   - "sudo pip install virtualenv"
   - "sudo pip install flake8"
   - "virtualenv ~/env"
   - "source ~/env/bin/activate"
   - "pip install nose"
   - pip install --process-dependency-links https://github.com/CloudifySource/cosmo-manager-rest-client/archive/feature/CLOUDIFY-2544-terminate-workflow.zip
   - "cd manager-rest && pip install --process-dependency-links . && cd .."
   - "cd workflows && pip install --process-dependency-links . && cd .."   

script:
   - "cd workflow-service; rake; cd .."
   - "flake8 vagrant/"
   - "flake8 manager-rest/"
   - "flake8 workflows/"
   - "nosetests manager-rest/manager_rest/test --nologcapture --nocapture"
   - "nosetests workflows/workflow_tests --nologcapture --nocapture -v"
