language: python

services:
  - rabbitmq # will start rabbitmq-server

python:
  - "2.7"


install:
    - echo "### Creating agent package..."
    - mkdir package
    - virtualenv package/env
    - source package/env/bin/activate
    - pip install https://github.com/CloudifySource/cosmo-plugin-agent-installer/archive/develop.zip --process-dependency-links
    - pip install https://github.com/CloudifySource/cosmo-plugin-plugin-installer/archive/develop.zip --process-dependency-links
    - tar czf agent.tar.gz package

    # celery needs the /dev/shm device for billiard semaphore functionality.
    # this device is not mounted by default on travis hosts.
    # see https://github.com/travis-ci/travis-core/issues/187#issuecomment-13682856
    - sudo test -d /dev/shm && sudo rm -rf /dev/shm
    - sudo ln -Tsf /{run,dev}/shm

    # command to install dependencies
    - pip install --process-dependency-links .

    - sudo pip install flake8
    - sudo pip install nose


before_script:
    - echo "### Starting HTTP server for serving agent package"
    - python -m SimpleHTTPServer 8000 &

script:
    - pip list
    - flake8 worker_installer
    - nosetests worker_installer.tests.test_configuration:CeleryWorkerConfigurationTest --nologcapture --nocapture
    - nosetests worker_installer.tests.test_worker_installer:TestLocalInstallerCase --nologcapture --nocapture

