language: python
python:
  - "2.7"

install:

    # command to install dependencies
    - python setup.py install


script:

    # command to run tests
    - python -m unittest plugin_installer.tests.test_installer