imports:
    - "cloudify.types"
    - "cloudmock.yaml"

blueprint:
    name: "simple_web_server"
    nodes:
        -   name: "webserver_host"
            type: "cloudify.types.host"
            interfaces:
                cloudify.interfaces.lifecycle:
                    - create: cloudmock.tasks.provision
                    - start: cloudmock.tasks.start
                    - stop: cloudmock.tasks.stop
                    - delete: cloudmock.tasks.terminate
                cloudify.interfaces.host:
                    - get_state: cloudmock.tasks.get_state
