imports:
    - "cloudify.types"
    - "cloudmock.yaml"

blueprint:
    name: "simple_web_server"
    topology:
        -   name: "webserver_host"
            type: "cloudify.types.host"
            interfaces:
                cloudify.interfaces.lifecycle:
                    - create: cloudmock.tasks.provision
                    - start: cloudmock.tasks.start
                    - stop: cloudmock.tasks.stop
                    - delete: cloudmock.tasks.terminate

workflows:
    mock_workflow:
        radial: |
            define mock_workflow
                execute_operation operation: 'make_mock_operation'

