imports:
    - "cloudify.types"
    - "testmockoperations.yaml"

blueprint:
    name: "single_node"
    nodes:
        -   name: "single_node"
            type: "mock_type"


types:
    mock_type:
        derived_from: cloudify.types.base
        interfaces:
            cloudify.interfaces.lifecycle:
                - start:
                      mapping: 'testmockoperations.tasks.get_resource_operation'
                      properties:
                          resource_path: 'basic.yaml'