imports:
  - "cloudify.types"
  - "cloudmock.yaml"

blueprint:
    name: multi_instance_many_different_hosts
    topology:
        -   name: host1
            type: test_host
            instances:
                deploy: 15
#        -   name: host2
#            type: test_host
#            instances:
#                deploy: 2
#        -   name: host3
#            type: test_host
#            instances:
#                deploy: 2

types:
    test_host:
        derived_from: cloudify.types.host
#        interfaces:
#            cloudify.interfaces.lifecycle:
#                - create: cloudmock.tasks.provision
#                - start: cloudmock.tasks.start
