imports:
    - "cloudify.types"
    - "testmockoperations.yaml"

blueprint:
    name: "single_unreachable_host"
    nodes:
        -   name: "single_node"
            type: "mock_type"


types:
    mock_type:
        derived_from: cloudify.types.base
        interfaces:
            mock_interface:
                - "touch": testmockoperations.tasks.touch
                - "make_reachable": testmockoperations.tasks.make_reachable
                - "make_unreachable": testmockoperations.tasks.make_unreachable
                - "set_property": testmockoperations.tasks.set_property
        workflows:
            create:
                radial: |
                    define mock_init
                        execute_operation operation: 'make_reachable'
            delete:
                radial: |
                    define mock_uninstall
                        execute_operation operation: 'make_unreachable'