imports:
    - "cloudify.types"
    - "cloudmock.yaml"

plugins:
    test_plugin:
        derived_from: "cloudify.plugins.agent_plugin"
        properties:
            url: "http://test_management_plugin.zip"

types:
    test_host:
        derived_from: cloudify.types.host
        properties:
            -   install_agent: true
            -   worker_config:
                    name: ${node_id}

blueprint:
    name: "simple_web_server"
    nodes:
        -   name: "webserver_host"
            type: test_host
            interfaces:
                cloudify.interfaces.lifecycle:
                    - create: cloudmock.tasks.provision
                    - start: cloudmock.tasks.start
                    - stop: cloudmock.tasks.stop
                    - delete: cloudmock.tasks.terminate
                cloudify.interfaces.test_lifecycle:
                    - create: test_plugin.tasks.start

workflows:
    mock_workflow:
        radial: |
            define mock_workflow
                execute_operation operation: 'make_mock_operation'

